# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Which is equivalent to
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$daml\
$deno\
$elixir\
$elm\
$fennel\
$gleam\
$golang\
$guix_shell\
$helm\
$java\
$julia\
$gradle\
$lua\
$nodejs\
$opa\
$python\
$rust\
$buf\
$nix_shell\
$conda\
$aws\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
[‚îî‚îÄ](bold green)\
$memory_usage\
$jobs\
$status$character"""

[git_branch]
disabled = false
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = '‚Ü™ '
#ignore_branches = ['main']

[git_metrics]
disabled = false

[git_state]
disabled = false

[status]
disabled = false
symbol = ''

[directory]
truncation_symbol = '../'
truncate_to_repo = false
style = 'dimmed cyan'
repo_root_style = 'bold cyan'
truncation_length = 3

[character]
success_symbol = '[‚û¢](bold green) '
error_symbol = '[‚®Ø](bold red) '

[nodejs]
format = '[$symbol($version )]($style)'
symbol = '‚¨° '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = 'python3'
detect_folders = ["!Workspaces"]

[memory_usage]
disabled = false
format = '$symbol[${ram_pct}]($style) '
symbol = 'üêè '
threshold = 80
style = 'bold dimmed green'
